### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by wnda** [seoscribe/editor#3]
@loisatwood @artmilt 

I'm not talking userfacing, but we could use a means to maintain contact and share code.

How are you with IRC? Do you what it is?

Alternatives if you're not familiar would be:

- Gitter
- Slack
- Discord
- Something self-hosted

What would you prefer? What do you know?

**Comment by loisatwood** [comment]
never used IRC

discord seems good for voice chat as well

don't know how good it works for code snippets

i'm sure any of them will be fine

**Comment by wnda** [comment]
Gitter it is then. Not sure where Arthur is...
